### ISSUE TITLE
Well, how can one use this to create a both way navigation? 

### ISSUE THREAD

**Issue by bluerid** [supersoniko/dynamodb-paginator#2]
It is working with `ExclusiveStartKey` inserted into the request. However, I couldn't see how can the previous results be loaded or move backward while doing pagination? 
```
{
  TableName: 'types',
  limit: '5',
  ExclusiveStartKey: { typeName: 'dog', breedName: 'american hairless terriers' }
}
```
@supersoniko

**Comment by supersoniko** [comment]
Hey @bluerid, so far I've only used this paginator for infinite scroll pagination. That way we never need to go back.
There's no official support to manage going backwards or going to a specific 'page' with this library. But you could save the previous cursors.

When I've the time I'll create official support for going backwards. You're also free to open a PR, that would be awesome.

**Comment by radixdt2024** [comment]
> It is working with `ExclusiveStartKey` inserted into the request. However, I couldn't see how can the previous results be loaded or move backward while doing pagination?
> 
> ```
> {
>   TableName: 'types',
>   limit: '5',
>   ExclusiveStartKey: { typeName: 'dog', breedName: 'american hairless terriers' }
> }
> ```
> 
> @supersoniko

Yes we need backward also

**Comment by supersoniko** [comment]
I'll try prepare a solution this October.

**Comment by supersoniko** [comment]
Update: gonna start development of this feature this month as I need it for one of my own projects.
Will post again on this issue when it's released.

**Comment by supersoniko** [comment]
Back navigation  supported in version 1.0.1.
Needs to be used on an index with a range key configured.
