### ISSUE TITLE
Please add disclaimer about the need for encryption and authentication

### ISSUE THREAD

**Issue by monken** [supersoniko/dynamodb-paginator#7]
You are opening yourself up to NoSQL injections by simply accepting the cursor from the client, decoding it and passing it to `dynamodb.query()`. The decoded cursor also includes your partition and sort key in plain text which could leak additional sensitive data. Your client can easily decode the cursor and inject their own query, potentially extracting any data from your table. One solution is to encrypt the cursor. To also prevent users from replaying a cursor, you should also add a message authentication code (MAC) to ensure that the cursor belongs to the same user.

**Comment by supersoniko** [comment]
Thanks for raising this concern in the documentation. I've added a security disclaimer in the documentation.
I'll be looking into providing an optional security measure built-in the library for ease of use and avoid people opening up themselves to attacks.
