### ISSUE TITLE
previousKeys

### ISSUE THREAD

**Issue by ievgen-boink** [supersoniko/dynamodb-paginator#8]
Every time a new paginated call is made, the encoded result becomes larger. Upon inspecting the cursor, I have noticed that a new item is added to the previousKeys object with each new paginated call. This eventually causes the object to become too large. Is there a way to prevent the saving of previous keys?

**Comment by supersoniko** [comment]
Hey

As far as I am aware if we want to support back navigation for DynamoDB results we need to keep track of the previous keys somewhere.

Currently the back navigation keys are indeed within the cursor itself, which could become troublesome if you go deep within the pagination.

I see 2 possible solutions:

- The package allows the user to save the back pagination keys in their own state management system through a configuration option. This could however introduce high complexity within the project using the package.
- The package makes back pagination optional, removing the back pagination keys as a whole when this option is enabled. However if the user has no need for back pagination, perhaps using the [AWS SDK directly](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/functions/paginatequery.html) is a better option than this package. But if this is a requested feature for the package, it's easy to implement.

Of course I'm open to any ideas to help with this issue

**Comment by ievgen-boink** [comment]
@supersoniko Hey, I like this idea: `The package makes back pagination optional`

**Comment by supersoniko** [comment]
> @supersoniko Hey, I like this idea: `The package makes back pagination optional`

I will release a new version early next week; making back navigation optional

**Comment by ievgen-boink** [comment]
Thanks a lot for fast answer

**Comment by supersoniko** [comment]
https://github.com/supersoniko/dynamodb-paginator/releases/tag/v2.2.0
